model_params: !!python/object/new:ml4floods.models.utils.configuration.AttrDict
  dictitems:
    hyperparameters:
      batch_size: 8
      channel_configuration: all
      early_stopping_patience: 15
      label_names:
      - land
      - water
      - cloud
      latent_dim: 64
      lr: 0.0003
      lr_decay: 0.1
      lr_patience: 15
      max_epochs: 1
      metric_monitor: train_iou_water
      metrics_to_track:
      - train_bce_loss
      - train_iou_land
      - train_iou_water
      - train_iou_cloud
      - train_loss
      model_type: segnet
      num_channels: 13
      num_classes: 3
      weight_per_class:
      - 1.93445299
      - 36.60054169
      - 2.19400729
    model_folder: "D:\\Documents\\coding\xC0\\ml4floods\xC0_Project\\models"
    model_version: v1
    test: false
    train: true
normalized_data: true
