model_params: !!python/object/new:ml4floods.models.utils.configuration.AttrDict
  dictitems:
    hyperparameters: !!python/object/new:ml4floods.models.utils.configuration.AttrDict
      dictitems:
        channel_configuration: all
        early_stopping_patience: 4
        label_names:
        - - invalid
          - clear
          - cloud
        - - invalid
          - land
          - water
        lr: 0.0001
        lr_decay: 0.5
        lr_patience: 2
        max_epochs: 10
        max_tile_size: 256
        metric_monitor: val_bce_land_water
        model_type: unet
        num_channels: 13
        num_classes: 2
        pos_weight:
        - 1.0
        - 20.0
        val_every: 1
        weight_problem:
        - 0.2
        - 0.8
    model_folder: models
    model_version: v2
    test: false
    train: true
normalized_data: true
