base_model: WorldFloodsModel
model_params: !!python/object/new:ml4floods.models.utils.configuration.AttrDict
  dictitems:
    hyperparameters:
      batch_size: 16
      channel_configuration: all
      early_stopping_patience: 12
      label_names:
      - land
      - water
      - cloud
      lr: 0.0003
      lr_decay: 0.1
      lr_patience: 5
      max_epochs: 10
      metric_monitor: val_iou water
      metrics_to_track:
      - val_dice_loss
      - val_bce_loss
      - val_iou_land
      - val_iou_water
      - val_iou_cloud
      - train_loss
      - val_loss
      model_type: unet
      num_channels: 13
      num_classes: 3
      weight_per_class:
      - 1.93445299
      - 2.75
      - 2.19400729
    model_folder: models
    model_version: v1
    test: false
    train: true
normalized_data: true
